use sys;
#1
CREATE TABLE CLASS(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(30)  NOT NULL);
#2
INSERT INTO CLASS(ID,NAME) 
VALUES (1, 'RAHUL');
SELECT*FROM CLASS;
#3
SELECT*FROM CLASS;
#4
START TRANSACTION;
UPDATE CLASS SET NAME='ABHIRAM' WHERE ID= 1;
SAVEPOINT A;
ROLLBACK TO A;
SELECT*FROM CLASS;
INSERT INTO CLASS VALUES (2, 'BEN');
SAVEPOINT B;
ROLLBACK TO B;
SELECT*FROM CLASS;
INSERT INTO CLASS VALUES (3, 'CRISTIANO');
SAVEPOINT C;
ROLLBACK TO C;
SELECT*FROM CLASS;
INSERT INTO CLASS VALUES (4, 'DHONI');
SAVEPOINT D;
ROLLBACK TO D;
SELECT*FROM CLASS;
INSERT INTO CLASS VALUES (5, 'EOIN');
SAVEPOINT E;
SELECT*FROM CLASS;
ROLLBACK TO E;
COMMIT;